# NumPy Exercise

Now that we've learned about NumPy's test your knowledge

Import NumPy

In [2]:
import numpy as np

Create an array of 10 zeros

In [8]:
arr = np.arange(0,10)
arr
arr * 0
# Wrong Answer Given

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of ones

In [11]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of Fives

In [12]:
arr_ones * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Create an array of the int from 10 to 50

In [20]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Create an array of the even int from 10 to 50

In [21]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3X3 matrix with values ranging from 0 to 8

In [22]:
np.arange([0,1,2],[3,4,5],[6,7,8])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [24]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create 3X3 Identity Matrix

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.randint(0,10)

5

In [33]:
np.random.rand(1)

array([0.55779539])

In [37]:
np.random.randn(25)

array([ 0.41647366, -0.14828331, -0.87289716, -1.05185087,  1.28217854,
       -0.90165507, -1.49555954,  2.34747256, -0.34928182, -0.78090361,
       -0.2200112 , -1.11722276, -0.20131292,  0.55877566,  1.20427802,
        1.58181483, -1.31898006,  0.78645002, -1.57677372,  0.92828749,
       -0.22848978,  0.60681443, -1.9051926 ,  1.82198057, -0.97302895])

In [40]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create Matrix from 0.01 to 1

In [41]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [42]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [46]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [69]:
mat[3,4]

20

In [81]:
mat[:3,1]

array([ 2,  7, 12])

In [80]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [82]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [83]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [84]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
np.sum(mat)

325

In [86]:
np.std(mat)

7.211102550927978

In [87]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])