In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_match = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_match)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.53570675, 0.64664769, 0.82282773, 0.23603539, 0.02513765])

In [16]:
np.random.rand(5,5)

array([[0.03509654, 0.51671587, 0.01666431, 0.12658874, 0.2823224 ],
       [0.89610047, 0.51828855, 0.06903035, 0.14741347, 0.32953718],
       [0.56913295, 0.33700666, 0.71621254, 0.13226925, 0.52430287],
       [0.32348165, 0.26790592, 0.13969792, 0.6601031 , 0.56669205],
       [0.31838554, 0.49891147, 0.8489169 , 0.88117228, 0.04030309]])

In [19]:
np.random.randn(2,3)

array([[ 2.87032976, -0.32202136,  0.32313224],
       [-0.38480354,  1.05479763, -0.0081517 ]])

In [23]:
np.random.randint(1,100,10)

array([76, 86, 62, 66, 81,  1, 33, 33, 30, 79])

In [25]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 9, 17, 49, 37, 35, 15, 25, 10, 37, 46])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

49

In [31]:
ranarr.min()

9

In [32]:
ranarr.argmax()

2

In [33]:
ranarr.argmin()

0

In [35]:
arr.shape

(25,)

In [37]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')